---
title: "WORKSHEET_2"
author: "BRYCE KENDRIC SALADAR"
date: "2022-10-06"
output: pdf_document
---

#1.Create a vector using : operator
hfill\break 
#a. Sequence from -5 to 5. Write the R code and its output. Describe its output.

output <- -5:5
 output
 [1] -5 -4 -3 -2 -1  0  1  2  3  4  5
 
 #b. x <- 1:7. What will be the value of x?
 x <- 1:7
 x
[1] 1 2 3 4 5 6 7
 
 # the value of x is the numbers 1 to 7
 
#2* Create a vector using seq() function
 
 #a. seq(1, 3, by=0.2) # specify step size
 #Write the R code and its output. Describe the output.
 
seq(1,3,by= 0.2)
 [1] 1.0 1.2 1.4 1.6 1.8 2.0 2.2 2.4 2.6 2.8 3.0
 
 #the value of the object are from 1 to 3 with a 0.2 gap
 
#3. A factory has a census of its workers. There are 50 workers #in total. The following
 list shows their ages: 34, 28, 22, 36, 27, 18, 52, 39, 42, 29, #35, 31, 27,
 22, 37, 34, 19, 20, 57, 49, 50, 37, 46, 25, 17, 37, 43, 53, 41, #51, 35,
 24,33, 41, 53, 40, 18, 44, 38, 41, 48, 27, 39, 19, 30, 61, 54, #58, 26,
 18.
 
  Workers <- c(34, 28, 22, 36, 27, 18, 52, 39, 42, 29, 35, 31, 27,22, 37, 34, 19, 20, 57, 49, 50, 37, 46, 25, 17, 37, 43, 53, 41, 51, 35, 24,33, 41, 53, 40, 18, 44, 38, 41, 48, 27, 39, 19, 30, 61, 54, 58, 26, 18)
  
 Workers
 [1] 34 28 22 36 27 18 52 39 42 29 35 31 27 22 37 34 19 20 57 49 50 37 46
[24] 25 17 37 43 53 41 51 35 24 33 41 53 40 18 44 38 41 48 27 39 19 30 61
[47] 54 58 26 18

#a. Access 3rd element, what is the value?
third_elem <- c(Workers[3])
 third_elem
[1] 22

#b. Access 2nd and 4th element, what are the values?
secforth_elem <- Workers[c(2,4)]
secforth_elem
[1] 28 36

#c. Access all but the 1st element is not included. Write the R code and its output.
 
all <- Workers[c(2:50)]
all
[1] 28 22 36 27 18 52 39 42 29 35 31 27 22 37 34 19
[17] 20 57 49 50 37 46 25 17 37 43 53 41 51 35 24 33
[33] 41 53 40 18 44 38 41 48 27 39 19 30 61 54 58 26
[49] 18

#4 *Create a vector x <- c("first"=3, "second"=0, "third"=9). Then named the #vector,names(x).

x <- c("first"=3, "second"=0, "third"=9)
x
 first second  third 
     3      0      9 
     
#a. Print the results. Then access x[c("first", "third")].Describe the output.
x <- x[c("first", "third")]
x
first third 
    3     9


